# Generated by Django 5.0.4 on 2024-05-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cout', models.IntegerField(default=0)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Histoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_deroulement', models.DateField()),
                ('date_fin', models.DateField(null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.commune')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='photos/Evenement')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoHistoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='photos/Histoire')),
                ('histoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.histoire')),
            ],
        ),
        migrations.CreateModel(
            name='RessourceNaturelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.commune')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRessourceNaturelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='photos/RessourceNaturelle')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ressourcenaturelle')),
            ],
        ),
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.commune')),
            ],
        ),
        migrations.CreateModel(
            name='PointCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.circuit')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.evenement')),
                ('res', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.ressourcenaturelle')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.sitetouristique')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='photos/SiteTouristique')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.sitetouristique')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=101)),
                ('date_naissance', models.DateField()),
                ('sexe', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photos/Utilisateur')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('statut', models.BooleanField(default=False)),
                ('montant_paye', models.PositiveIntegerField(default=0)),
                ('date_reservation', models.DateField(auto_now=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.circuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.sitetouristique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ressourcenaturelle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireHistoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('histoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.histoire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='circuit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur'),
        ),
    ]
