# Generated by Django 5.0.4 on 2024-05-05 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_deroulement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Histoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.departement')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/Evenement')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoHistoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/Histoire')),
                ('histoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.histoire')),
            ],
        ),
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.commune')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/SiteTouristique')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.sitetouristique')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=101)),
                ('date_naissance', models.DateField()),
                ('sexe', models.BooleanField(default=True)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.profil')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.sitetouristique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireHistoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('histoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.histoire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
    ]
