# Generated by Django 5.0.4 on 2024-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_commentaireevent_date_ajout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='login',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
