# Generated by Django 5.0.4 on 2024-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_utilisateur_login_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/Utilisateur'),
        ),
    ]
