# Generated by Django 5.0.4 on 2024-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoevenement',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photohistoire',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photosite',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
