# Generated by Django 5.0.4 on 2024-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_ressourcenaturelle_photoressourcenaturelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
