# Generated by Django 5.0.4 on 2024-05-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_evenement_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='commune',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.commune'),
            preserve_default=False,
        ),
    ]
