# Generated by Django 5.0.4 on 2024-05-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_circuit_pointcircuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='cout',
            field=models.IntegerField(default=0),
        ),
    ]
