# Generated by Django 5.0.4 on 2024-05-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_circuit_cout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointcircuit',
            name='hist',
        ),
    ]
