# Generated by Django 5.0.4 on 2024-05-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_pointcircuit_hist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('statut', models.BooleanField(default=False)),
                ('montant_paye', models.PositiveIntegerField(default=0)),
                ('date_reservation', models.DateField(auto_now=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.circuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur')),
            ],
        ),
    ]
