# Generated by Django 5.0.4 on 2024-05-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circuit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.utilisateur'),
        ),
    ]
