# Generated by Django 5.0.4 on 2024-05-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_circuit_is_special_circuit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaireevent',
            old_name='site',
            new_name='event',
        ),
    ]
